definitions:
  thttp.ResponseWithDetails-string:
    properties:
      description:
        type: string
      error_code:
        type: integer
      ok:
        type: boolean
      result:
        type: string
    type: object
info:
  contact: {}
  description: API Server for application
  title: Test task Swartway
  version: "1.0"
paths:
  /api/ping:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/thttp.ResponseWithDetails-string'
      summary: Пинг сервиса
      tags:
      - Служебные
swagger: "2.0"
