definitions:
  test-task-sw_service_models.Department:
    properties:
      department_name:
        type: string
      department_phone:
        type: string
    type: object
  test-task-sw_service_models.Employee:
    properties:
      company_id:
        type: integer
      department:
        $ref: '#/definitions/test-task-sw_service_models.Department'
      id:
        type: integer
      name:
        type: string
      passport:
        $ref: '#/definitions/test-task-sw_service_models.Passport'
      phone:
        type: string
      surname:
        type: string
    type: object
  test-task-sw_service_models.Passport:
    properties:
      passport_number:
        type: string
      passport_type:
        type: string
    type: object
  thttp.ResponseError:
    properties:
      description:
        type: string
      error_code:
        type: integer
      ok:
        type: boolean
      result: {}
    type: object
  thttp.ResponseOk:
    properties:
      description:
        type: string
      error_code:
        type: integer
      ok:
        type: boolean
      result: {}
    type: object
  thttp.ResponseWithDetails-array_test-task-sw_service_models_Employee:
    properties:
      description:
        type: string
      error_code:
        type: integer
      ok:
        type: boolean
      result:
        items:
          $ref: '#/definitions/test-task-sw_service_models.Employee'
        type: array
    type: object
  thttp.ResponseWithDetails-string:
    properties:
      description:
        type: string
      error_code:
        type: integer
      ok:
        type: boolean
      result:
        type: string
    type: object
  thttp.ResponseWithDetails-test-task-sw_service_models_Employee:
    properties:
      description:
        type: string
      error_code:
        type: integer
      ok:
        type: boolean
      result:
        $ref: '#/definitions/test-task-sw_service_models.Employee'
    type: object
info:
  contact: {}
  description: API Server for application
  title: Test task Swartway
  version: "1.0"
paths:
  /api/employee/create:
    post:
      consumes:
      - application/json
      parameters:
      - description: Данные пользователя
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/test-task-sw_service_models.Employee'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Создание работника
      tags:
      - Employee
  /api/employee/delete/{employeeId}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Идентификатор работника
        in: path
        name: employeeId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/thttp.ResponseOk'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/thttp.ResponseError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/thttp.ResponseError'
      summary: Удаление работника
      tags:
      - Employee
  /api/employee/list/company/{companyId}:
    get:
      consumes:
      - application/json
      parameters:
      - description: Идентификатор компании
        in: path
        name: companyId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/thttp.ResponseWithDetails-array_test-task-sw_service_models_Employee'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/thttp.ResponseError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/thttp.ResponseError'
      summary: Получение работников по id компании
      tags:
      - Employee
  /api/employee/list/department/{depName}:
    get:
      consumes:
      - application/json
      parameters:
      - description: Название отдела
        in: path
        name: depName
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/thttp.ResponseWithDetails-array_test-task-sw_service_models_Employee'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/thttp.ResponseError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/thttp.ResponseError'
      summary: Получение работников по отделу
      tags:
      - Employees
  /api/employee/update/{employeeId}:
    put:
      consumes:
      - application/json
      parameters:
      - description: Идентификатор работника
        in: path
        name: employeeId
        required: true
        type: string
      - description: Данные для обновления работника
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/test-task-sw_service_models.Employee'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/thttp.ResponseWithDetails-test-task-sw_service_models_Employee'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/thttp.ResponseError'
        "409":
          description: Already exists
          schema:
            $ref: '#/definitions/thttp.ResponseError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/thttp.ResponseError'
      summary: Изменение данных работника
      tags:
      - Employee
  /api/ping:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/thttp.ResponseWithDetails-string'
      summary: Пинг сервиса
      tags:
      - Служебные
swagger: "2.0"
